### ISSUE TITLE
Instructions for data2text-macro-plan-py

### ISSUE THREAD

**Issue by TongLi3701** [ratishsp/data2text-macro-plan-py#1]
Hi @ratishsp,

Thanks for providing the code for your paper. I am trying to learn more about this method and run the code, but I do not see many instructions like the other repos such as https://github.com/ratishsp/data2text-plan-py.

I just wonder how can I run the inference pipeline? 

I can see the structure is quite similar with https://github.com/ratishsp/data2text-plan-py.

So if I want to run the code, shall I follow the same instructions?

Many thanks

**Comment by ratishsp** [comment]
Hi Tong, 
Thanks for the interest in the project. 
The code structure is indeed similar to https://github.com/ratishsp/data2text-plan-py but with differences too (two stage model, newer code etc.)
I had got busy with another work, I will push code into this repository over the next few days. And will update the README accordingly. 
If you are interested in model outputs to compare with your own outputs, I have added them in the google drive link https://drive.google.com/drive/folders/1jJjq5IvuBKNLTAe7fuwlDYParrxpK-WD?usp=sharing

**Comment by TongLi3701** [comment]
Hi,

Thanks for your kind reply.
That will be really helpful.

Best wishes
Tong

**Comment by ratishsp** [comment]
Hi Tong,
I have updated the README with the instructions for RotoWire dataset. The instructions for MLB dataset will follow soon. 
Regards,
Ratish

**Comment by TongLi3701** [comment]
Hi @ratishsp ,

Thanks a lot for your contribution.

That is really helpful

**Comment by ratishsp** [comment]
The repo has been updated with instructions for MLB dataset too.
