### ISSUE TITLE
Missing ordinal_adjective_map_file for MLB experiments

### ISSUE THREAD

**Issue by ashishu007** [ratishsp/data2text-macro-plan-py#3]
Hi @ratishsp,

Thanks a lot for the great paper & code. The experiments for RotoWire are fine, but with MLB I think some file is missing here. Pls see the error below:

(`macro_plan` directory is the `main` branch's code)

```bash
Traceback (most recent call last):
  File "./macro_plan/scripts/create_mlb_target_data.py", line 160, in <module>
    process(args.json_root, args.dataset_type, args.ordinal_adjective_map_file, args.output_folder)
  File "./macro_plan/scripts/create_mlb_target_data.py", line 20, in process
    ordinal_adjective_map = get_ordinal_adjective_map(ordinal_adjective_map_file)
  File "/check/data2text-macro/macro_plan/scripts/mlb_utils.py", line 556, in get_ordinal_adjective_map
    ordinal_adjective_map_file = open(ordinal_adjective_map_file_name, mode="r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './macro_plan/data/traintokens-ordinaladjective-inning-identifier'
```

Is there something obvious I'm missing here?

Thanks!

**Comment by ashishu007** [comment]
Hi, got those files here (from [MLB-IE](https://github.com/ratishsp/mlb-ie) repo):

https://drive.google.com/drive/folders/19u99YQqoG7K4xIq9XdeZgPGr2jvQSCIe?usp=sharing

Closing the issue now.

**Comment by ratishsp** [comment]
Thanks for the feedback!
I have also made couple of commits (https://github.com/ratishsp/data2text-macro-plan-py/commit/3564e0c04e65d6708255f8b0e58eef5ee9cf60e9) which help create the ordinal adjective map file during summary evaluation.

**Comment by ashishu007** [comment]
That's great! I was going to ask about the creation of ordinal adjective map files for IE evaluation.
So thanks again.
