### ISSUE TITLE
hot to create the file [ordinal_adjective_map_file_name]?

### ISSUE THREAD

**Issue by llllearner** [ratishsp/data2text-macro-plan-py#4]
https://github.com/ratishsp/data2text-macro-plan-py/blob/bb01ec6e23dab28c1e969f23bd55776b597fb995/scripts/mlb_utils.py#L556

**Comment by llllearner** [comment]
i can't find any instructions about this problem in [README_MLB.md](https://github.com/ratishsp/data2text-macro-plan-py/blob/main/README_MLB.md)

**Comment by ratishsp** [comment]
Hi, the files are [here](https://drive.google.com/drive/folders/19u99YQqoG7K4xIq9XdeZgPGr2jvQSCIe?usp=sharing). Please also refer #3.

**Comment by llllearner** [comment]
> Hi, the files are [here](https://drive.google.com/drive/folders/19u99YQqoG7K4xIq9XdeZgPGr2jvQSCIe?usp=sharing). Please also refer #3.

thanks a lot.
